oauth.token.lifetime.access-minutes=10
oauth.token.lifetime.id-minutes=5
oauth.token.lifetime.refresh-minutes=1440

code.lifetime-minutes=10

client.lifetime-days=90

rsa.key-size=2048

timezone.offset-hours=9

user.default-scope=openid profile email
