spring.message_resource.basename=/conf/messages
spring.message_resource.encoding=UTF-8

domain.web=https://tokyomap.live

docker.container.auth=http://tokyomap-oauth:8080
docker.container.resource=http://tokyomap-resource:8081

registration.admin.username=${REGISTRATION_ADMIN_USERNAME}
registration.admin.password=${REGISTRATION_ADMIN_PASSWORD}
registration.endpoint=https://tokyomap.live/auth/api/v1/register
