spring.message_resource.basename=/conf/messages
spring.message_resource.encoding=UTF-8

domain.as=https://as.localhost
domain.rs=https://rs.localhost

registration.admin.username=admin
registration.admin.password=password
registration.endpoint=https://as.localhost/api/v1/register
