spring.message_resource.basename=/conf/messages
spring.message_resource.encoding=UTF-8

domain.idp=https://tallyme-idp.localhost
domain.resource=https://tallyme-resource.localhost

registration.admin.username=admin
registration.admin.password=password
registration.endpoint=https://tallyme-idp.localhost/api/v1/register
